rustore_remote_config_network_request_failure – вызывается при ошибке сетевого запроса Remote Config.Для запуска слушателя перечисленных событий используйте метод init_event_listener.Подписка на событияfunction init(self)	rustorecore.connect("rustore_get_remote_config_success", _on_get_remote_config_success)	rustorecore.connect("rustore_get_remote_config_failure", _on_get_remote_config_failure)	rustorecore.connect("rustore_rustore_background_job_errors", _on_rustore_background_job_errors)	rustorecore.connect("rustore_first_load_complete", _on_rustore_first_load_complete)	rustorecore.connect("rustore_init_complete", _on_rustore_init_complete)	rustorecore.connect("rustore_memory_cache_updated", _on_rustore_memory_cache_updated)	rustorecore.connect("rustore_persistent_storage_updated", _on_rustore_persistent_storage_updated)	rustorecore.connect("rustore_remote_config_network_request_failure", _on_rustore_remote_config_network_request_failure)	rustoreremoteconfig.init_event_listener()endfunction _on_rustore_background_job_errors(self, channel, value)	local data = json.decode(value)endfunction _on_rustore_first_load_complete(self, channel, value)endfunction _on_rustore_init_complete(self, channel, value)endfunction _on_rustore_memory_cache_updated(self, channel, value)endfunction _on_rustore_persistent_storage_updated(self, channel, value)endfunction _on_rustore_remote_config_network_request_failure(self, channel, value)	local data = json.decode(value)endОбратные вызовы (callbacks) rustore_background_job_errors и rustore_remote_config_network_request_failure возвращают строку JSON с информацией об ошибке. Структра данных ошибки описана в разделе Возможные ошибки.